const double SINGLE_PAGE_FIXED_HEIGHT = 650;
const double SINGLE_PAGE_TEXT_SIZE = 18.0;
const double PIXEL_WIDTH_1_COLUMN = 650;
const double PIXEL_WIDTH_2_COLUMNS = 1350;
const double PIXEL_WIDTH_3_COLUMNS = 1750;
const double PIXEL_FIXED_DRAWER = 950;