name: linux_build

on:
  push:
    branches:
      - linux_ci

jobs:
  test:
    name: Windows build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Visual Studio
      uses: actions/setup-dotnet@v1

    - name: Setup Flutter
      uses: subosito/flutter-action@v1.5.3
      with:
        channel: stable

    - name: Enable windows build
      run: flutter config --enable-windows-desktop

    - name: Flutter doctor
      run: flutter doctor

    - name: Download pub dependencies
      run: flutter pub get

    - name: Build for windows
      run: flutter build windows