name: linux_build

on:
  push:
    branches:
      - linux_ci

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install missing packages
      run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev

    - name: Setup Flutter
      uses: subosito/flutter-action@v1.5.3
      with:
        channel: stable

    - name: Enable linux build
      run: flutter config --enable-linux-desktop

    - name: Flutter version
      run: flutter --version

    - name: Download pub dependencies
      run: flutter pub get

    - name: Build for linux
      run: flutter build linux