name: "Integration testing"

on: [push, pull_request]

jobs:
  desktop_integration_testing:
    name: Desktop integration testing
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install missing packages
      run: |
        sudo apt update
        sudo apt install -y clang cmake ninja-build pkg-config libgtk-3-dev

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true
        channel: stable

    - name: Flutter doctor
      run: flutter doctor --verbose

    - name: Install Melos and bootstrap (get the dependencies)
      run: |
        dart pub global activate melos
        melos bootstrap

    - name: Run integration testing
      run: |
        export DISPLAY=:99
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        flutter test integration_test/large_display_test.dart -d linux