name: Build and Deploy
on:
  push:
    branches:
      - web_cicd
jobs:
  build_pwa:
    name: Build PWA
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1.5.3
      with:
        channel: stable

    - name: Flutter version
      run: flutter --version

    - name: Download pub dependencies
      run: flutter pub get

    - name: Compile for web
      run: flutter build web

    - name: Upload to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONVERTER_NOW }}'
        channelId: live
        projectId: converter-now