name: Build and Deploy
on:
  push:
    branches:
      - name: web_cicd
jobs:
  build_pwa:
    name: Build PWA
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Flutter
      uses: subosito/flutter-action@v1.5.3
      with:
        channel: stable
    - name: Download pub dependencies
      run: flutter pub get
    - name: Build
      run: flutter build web
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v2.0.0
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}