name: Build and Deploy
on:
  push:
    branches:
      - web_cicd
jobs:
  build_pwa:
    name: Build PWA
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - run: flutter build web
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONVERTER_NOW }}'
        channelId: live
        projectId: converter-now